ContractsManager/Models/Contract.cs
using System.ComponentModel.DataAnnotations;

namespace ContractsManager.Models
{
    public class Contract
    {
        [Key]
        public int Id { get; set; }

        [Required, MaxLength(128)]
        public string Code { get; set; }

        [Required, MaxLength(128)]
        public string Name { get; set; }

        [Required, MaxLength(128)]
        public string Customer { get; set; }

        public List<ContractStage> Stages { get; set; }
        public Contract()
        {
            Stages = new List<ContractStage>();
        }
    }
}

ContractsManager/Models/ContractStage.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContractsManager.Models
{
    public class ContractStage
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int ContractId { get; set; }

        [Required, MaxLength(128)]
        public string StageName { get; set; }

        [Required, Column(TypeName = "date")]
        public DateOnly StartDate;

        [Required, Column(TypeName = "date")]
        public DateOnly EndDate;
    }
}

ContractsManager/Controllers/GetContractStagesController.cs
using ContractsManager.Models;
using ContractsManager.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ContractsManager.Controllers
{
    [ApiController]
    [Route("/api/Contracts/[controller]")]
    public class GetContractStagesController : ControllerBase
    {
        [HttpGet("{contractID:int}")]
        public async Task<IAsyncEnumerable<ContractStage>> GetContractStages(int contractID)
        {
            DBContext context = new DBContext();
            return context.contractstages.Where(s => s.ContractId == contractID).AsAsyncEnumerable();
        }
    }
}

ContractsManager/Controllers/GetContractsController.cs
using ContractsManager.Models;
using ContractsManager.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ContractsManager.Controllers
{
    [ApiController]
    [Route("/api/Contracts/[controller]")]
    public class GetContractsController : ControllerBase
    {
        [HttpGet]
        public async Task<IAsyncEnumerable<Contract>> GetContracts()
        {
            DBContext context = new DBContext();
            return context.contracts.Include(s => s.Stages).AsAsyncEnumerable();
        }
    }
}

ContractsManager/Controllers/UploadFileController.cs
using ContractsManager.Models;
using ContractsManager.Scripts;
using ContractsManager.Services;
using Microsoft.AspNetCore.Mvc;

namespace ContractsManager.Controllers
{
    [ApiController]
    [Route("/api/Import/[controller]")]
    public class UploadFileController : ControllerBase
    {
        [HttpPost]
        public async Task<IActionResult> Import(IFormFile file)
        {
            string fileExtension = Path.GetExtension(file.FileName);
            if (file == null)
                return Content("Не выбран файл");
            if (fileExtension != ".xls" && fileExtension != ".xlsx")
                return Content("Неверный формат файла");

            Stream stream = file.OpenReadStream();
            List<Contract> contracts = await Task.Run(() =>
            {
                ExcelReader excelReader = new ExcelReader(stream);
                return excelReader.GetContractsFromExcel();
            });

            DBContext dbContext = new DBContext();
            await dbContext.contracts.AddRangeAsync(contracts);
            await dbContext.SaveChangesAsync();

            string addedContent = "";
            foreach (Contract contract in contracts)
            {
                addedContent += $"Добавлен контракт со значениями:\nID: {contract.Id};\n";
                addedContent += $"Шифр: {contract.Code};\n";
                addedContent += $"Название: {contract.Name};\n";
                addedContent += $"Заказчик: {contract.Customer};\n";

                addedContent += "Этапы проекта:\n";
                string contractStages = "";
                foreach (ContractStage stage in contract.Stages)
                {
                    contractStages += "Добавлен этап контракта со значениями:\n";
                    contractStages += $"ID контракта: {stage.ContractId};\n";
                    contractStages += $"Название этапа: {stage.StageName};\n";
                    contractStages += $"Дата начала: {stage.StartDate};\n";
                    contractStages += $"Дата окончания: {stage.EndDate}.\n\n";
                }
                addedContent += contractStages;
                addedContent += $"Количество этапов: {contract.Stages.Count}.\n\n\n";
            }

            return Content(addedContent);
        }
    }
}

ContractsManager/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ContractsManager.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ContractsManager/Pages/Import.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContractsManager.Pages
{
    public class ImportModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ContractsManager/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContractsManager.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ContractsManager/Pages/Import.cshtml
@page "/Contracts/Import"
@model ImportModel
@{
    ViewData["Title"] = "Import File";
}
<h1>Import File</h1>

@using (Html.BeginForm("Import", "UploadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" />
    <input type="submit" value="OK" />
}

ContractsManager/Pages/Index.cshtml
@page "/Contracts/Index"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script type="text/javascript">
	loadData();

	function loadData() {
		$.ajax({
			url: '/api/Contracts/GetContracts',
			type: "GET",
			dataType: "json",
			success: function (data, status) {
				$(".table").append(drawTable(data));
			}
		});
	}

	function drawRow(rowData) {
		var row = $("<tr>");

		row.append($("<td>" + rowData.id + "</td>"));
		row.append($("<td>" + rowData.code + "</td>"));
		row.append($("<td>" + rowData.name + "</td>"));
		row.append($("<td>" + rowData.customer + "</td>"));
		row.append($("<td>" + rowData.stages.map((stage) => " " + stage.stageName) + "</td>"));

		row.append($("</tr>"));

		return row;
	}

	function drawTable(data) {
		var rows = [];

		for (var i = 0; i < data.length; i++) {
			rows.push(drawRow(data[i]));
		}

		$(".table").append(rows);
	}
</script>

<div class="text-center">
    <main>
		<div class="container" style="height:1300px;">
			<div>
				<div>
					<table class="table">
						<tr>
							<th scope="col">Идентификатор</th>
							<th scope="col">Шифр</th>
							<th scope="col">Название</th>
							<th scope="col">Наименование</th>
							<th scope="col">Стадии</th>
						</tr>
					</table>
				</div>
			</div>
		</div>
		@Html.ActionLink(
		"Get Contracts",
		"GetContracts",
		"GetContracts"
		)
		@Html.ActionLink(
		"Get Contract Stages (ID = 1)",
		"GetContractStages",
		"GetContractStages",
		new { contractID = 1 }
		)
	</main>
</div>

ContractsManager/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContractsManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContractsManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ContractsManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Import">Import</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ContractsManager - <a asp-area="" asp-page="/Import">Import</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>